import { z } from 'zod';
import { CaseEventType, CaseStatus, CaseType, InvoiceStatus } from '../generated/prisma/enums.js';
import { DateInputSchema, PaginationSchema } from './common.js';

export const CaseTypeSchema = z.enum(CaseType, { message: 'Хэргийн төрөл буруу байна' });
export const CaseStatusSchema = z.enum(CaseStatus, { message: 'Хэргийн төлөв буруу байна' });
export const InvoiceStatusSchema = z.enum(InvoiceStatus, { message: 'Нэхэмжлэхийн төлөв буруу байна' });

export const CaseEventTypeSchema = z.enum(CaseEventType, { message: 'Үйл явдлын төрөл буруу байна' });

export const CaseQuerySchema = PaginationSchema.extend({
  status: CaseStatusSchema.optional(),
  type: CaseTypeSchema.optional(),
  search: z.string().trim().max(100).optional(),
  /** Staff filters — always intersected with the caller's scope. */
  clientId: z.uuid().optional(),
  lawyerId: z.uuid().optional(),
});
export type CaseQueryInput = z.infer<typeof CaseQuerySchema>;

export const InvoiceQuerySchema = PaginationSchema.extend({
  status: InvoiceStatusSchema.optional(),
  caseId: z.uuid().optional(),
});
export type InvoiceQueryInput = z.infer<typeof InvoiceQuerySchema>;

/** Multipart form fields accompanying a document upload. */
export const UploadDocumentSchema = z.object({
  name: z.string().trim().min(1).max(255).optional(),
  isVisibleToClient: z
    .union([z.boolean(), z.enum(['true', 'false'])])
    .transform((value) => value === true || value === 'true')
    .default(true),
});
export type UploadDocumentInput = z.infer<typeof UploadDocumentSchema>;

export const ALLOWED_DOCUMENT_MIME_TYPES = [
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'image/jpeg',
  'image/png',
  'text/plain',
] as const;

export const MAX_DOCUMENT_SIZE_BYTES = 20 * 1024 * 1024; // 20 MB

// ─── Staff (ADMIN / LAWYER) case management ─────────────────────────────────

const CaseTitleSchema = z.string().trim().min(5, 'Хэргийн нэр хамгийн багадаа 5 тэмдэгт байна').max(200, 'Хэргийн нэр хэт урт байна');
const CaseDescriptionSchema = z.string().trim().max(5000, 'Тайлбар хэт урт байна');

/** POST /cases — caseNumber is generated by the API; LAWYER may only assign themselves. */
export const CreateCaseSchema = z.object({
  title: CaseTitleSchema,
  description: CaseDescriptionSchema.nullable().optional(),
  type: CaseTypeSchema,
  clientId: z.uuid({ message: 'Харилцагч сонгоно уу' }),
  lawyerId: z.uuid({ message: 'Хуульч сонгоно уу' }).optional(),
  openedAt: DateInputSchema.optional(),
});
export type CreateCaseInput = z.infer<typeof CreateCaseSchema>;

/** PATCH /cases/:id — a status change is recorded as a STATUS_CHANGE event. */
export const UpdateCaseSchema = z
  .object({
    title: CaseTitleSchema,
    description: CaseDescriptionSchema.nullable(),
    type: CaseTypeSchema,
    status: CaseStatusSchema,
    lawyerId: z.uuid({ message: 'Хуульч сонгоно уу' }),
  })
  .partial();
export type UpdateCaseInput = z.infer<typeof UpdateCaseSchema>;

/** PATCH /cases/:id/close */
export const CloseCaseSchema = z.object({
  note: z.string().trim().max(1000, 'Тэмдэглэл хэт урт байна').optional(),
});
export type CloseCaseInput = z.infer<typeof CloseCaseSchema>;

/** STATUS_CHANGE events are created by the API only. */
export const MANUAL_CASE_EVENT_TYPES = ['NOTE', 'HEARING', 'MEETING', 'DEADLINE', 'DOCUMENT'] as const;
export const ManualCaseEventTypeSchema = z.enum(MANUAL_CASE_EVENT_TYPES, { message: 'Үйл явдлын төрөл буруу байна' });

/** Event types that notify the client when visible to them. */
export const CLIENT_NOTIFY_EVENT_TYPES: readonly CaseEventType[] = ['HEARING', 'MEETING', 'DEADLINE'];

const EventTitleSchema = z.string().trim().min(3, 'Гарчиг хамгийн багадаа 3 тэмдэгт байна').max(200, 'Гарчиг хэт урт байна');
const EventDescriptionSchema = z.string().trim().max(4000, 'Тайлбар хэт урт байна');

export const CreateCaseEventSchema = z.object({
  type: ManualCaseEventTypeSchema,
  title: EventTitleSchema,
  description: EventDescriptionSchema.nullable().optional(),
  eventDate: DateInputSchema,
  isVisibleToClient: z.boolean().default(true),
});
export type CreateCaseEventInput = z.infer<typeof CreateCaseEventSchema>;

// Defined field by field (no defaults) so a PATCH never resets omitted fields.
export const UpdateCaseEventSchema = z
  .object({
    type: ManualCaseEventTypeSchema,
    title: EventTitleSchema,
    description: EventDescriptionSchema.nullable(),
    eventDate: DateInputSchema,
    isVisibleToClient: z.boolean(),
  })
  .partial();
export type UpdateCaseEventInput = z.infer<typeof UpdateCaseEventSchema>;
